twig:
    globals:
        menu:
            main:
                dashboard:
                    name: 'Dashboard'
                    url: 'dashboard'
                    icon: 'dashboard'
                interviewers:
                    name: 'Encuestadores'
                    url: 'interviewer_list'
                    icon: 'list-alt'
                project:
                    name: 'Proyectos'
                    url: 'project_list'
                    icon: 'tasks'
                invoices:
                    name: 'Facturas'
                    url: 'invoice_list'
                    icon: 'folder-open'