twig:
    globals:
        menu:
            main:
                dashboard:
                    name: 'Dashboard'
                    url: 'dashboard'
                    role: 'ROLE_USER'
                    icon: 'dashboard'
                interviewers:
                    name: 'Encuestadores'
                    url: 'devtag_kleffmann_interviewer_index'
                    role: 'ROLE_INTERVIEWER'
                    icon: 'list-alt'
                project:
                    name: 'Proyectos'
                    url: 'devtag_kleffmann_project_index'
                    role: 'ROLE_PROJECT_MANAGER'
                    icon: 'tasks'
                invoices:
                    name: 'Facturas'
                    url: 'devtag_kleffmann_invoice_index'
                    role: 'ROLE_ADMINISTRATION'
                    icon: 'folder-open'
                training:
                    name: 'Capacitaciones'
                    url: 'devtag_kleffmann_training_index'
                    role: 'ROLE_ADMIN'
                    icon: 'book'
                users:
                    name: 'Usuarios'
                    url: 'devtag_kleffmann_user_index'
                    role: 'ROLE_ADMIN'
                    icon: 'user'
                catalog:
                    name: 'Catálogos'
                    url: 'dashboard'
                    role: 'ROLE_ADMIN'
                    icon: 'files-o'
                    submenu:
                        bank:
                            name: 'Bancos'
                            url: 'devtag_kleffmann_bank_index'
                        customer:
                            name: 'Clientes'
                            url: 'devtag_kleffmann_customer_index'
                        manager:
                            name: 'Gerentes'
                            url: 'devtag_kleffmann_manager_index'
                        status:
                            name: 'Estatus de Proyectos'
                            url: 'devtag_kleffmann_status_index'
                        project_type:
                            name: 'Tipos de Proyectos'
                            url: 'devtag_kleffmann_projecttype_index'
                        project_type_uprising:
                            name: 'Tipos de Levantamientos'
                            url: 'devtag_kleffmann_projecttypeuprising_index'