twig:
    globals:
        menu:
            main:
                dashboard:
                    name: 'Dashboard'
                    url: 'dashboard'
                    role: 'ROLE_USER'
                    icon: 'dashboard'
                interviewers:
                    name: 'Encuestadores'
                    url: 'interviewers'
                    role: 'ROLE_INTERVIEWER'
                    icon: 'list-alt'
                project:
                    name: 'Proyectos'
                    url: 'projects'
                    role: 'ROLE_PROJECT_MANAGER'
                    icon: 'tasks'
                invoices:
                    name: 'Facturas'
                    url: 'invoices'
                    role: 'ROLE_ADMINISTRATION'
                    icon: 'folder-open'
                training:
                    name: 'Capacitaciones'
                    url: 'trainings'
                    role: 'ROLE_ADMIN'
                    icon: 'book'
                users:
                    name: 'Usuarios'
                    url: 'users'
                    role: 'ROLE_ADMIN'
                    icon: 'user'
                catalog:
                    name: 'Catálogos'
                    url: 'dashboard'
                    role: 'ROLE_ADMIN'
                    icon: 'files-o'
                    submenu:
                        bank:
                            name: 'Bancos'
                            url: 'banks'
                        customer:
                            name: 'Clientes'
                            url: 'customers'
                        manager:
                            name: 'Gerentes'
                            url: 'managers'
                        project_type:
                            name: 'Tipos de Proyectos'
                            url: 'project_types'
                        status:
                            name: 'Estatus'
                            url: 'status_list'