security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_USER: ~
        ROLE_PROJECT_MANAGER: ROLE_USER
        ROLE_INTERVIEWER:     ROLE_USER
        ROLE_ADMINISTRATION:  ROLE_INTERVIEWER
        ROLE_ADMIN:           [ROLE_USER, ROLE_PROJECT_MANAGER, ROLE_INTERVIEWER, ROLE_ADMINISTRATION]
        ROLE_SUPER_ADMIN:     [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: devtag, roles: [ 'ROLE_USER' ] }
                    interviewer:  { password: devtag, roles: [ 'ROLE_INTERVIEWER' ] }
                    project_manager:  { password: devtag, roles: [ 'ROLE_PROJECT_MANAGER' ] }
                    administration:  { password: devtag, roles: [ 'ROLE_ADMINISTRATION' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: _kleffmann_security_check
                login_path: _kleffmann_login
            logout:
                path:   _kleffmann_logout
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
