services:
    # controllers
    kleffmann.interviewer.controller:
        class: DevTag\KleffmannBundle\Controller\InterviewerController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setInterviewerService, ['@kleffmann.interviewer.service']]
            - [ setInterviewerRepository, ['@kleffmann.interviewer.repository']]

    kleffmann.interviewer_zone.controller:
        class: DevTag\KleffmannBundle\Controller\InterviewerZoneController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setInterviewerZoneService, ['@kleffmann.interviewer_zone.service']]
            - [ setInterviewerZoneRepository, ['@kleffmann.interviewer_zone.repository']]

    kleffmann.project.controller:
        class: DevTag\KleffmannBundle\Controller\ProjectController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setProjectService, ['@kleffmann.project.service']]
            - [ setProjectRepository, ['@kleffmann.project.repository']]

    kleffmann.project_zone.controller:
        class: DevTag\KleffmannBundle\Controller\ProjectZoneController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setProjectZoneService, ['@kleffmann.project_zone.service']]
            - [ setProjectZoneRepository, ['@kleffmann.project_zone.repository']]

    kleffmann.project_filter.controller:
        class: DevTag\KleffmannBundle\Controller\ProjectFilterController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setProjectFilterService, ['@kleffmann.project_filter.service']]
            - [ setProjectFilterRepository, ['@kleffmann.project_filter.repository']]

    kleffmann.project_variable.controller:
        class: DevTag\KleffmannBundle\Controller\ProjectVariableController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]

    kleffmann.invoice.controller:
        class: DevTag\KleffmannBundle\Controller\InvoiceController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setInvoiceService, ['@kleffmann.invoice.service']]
            - [ setInvoiceRepository, ['@kleffmann.invoice.repository']]

    kleffmann.customer.controller:
        class: DevTag\KleffmannBundle\Controller\CustomerController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setCustomerService, ['@kleffmann.customer.service']]
            - [ setCustomerRepository, ['@kleffmann.customer.repository']]

    kleffmann.manager.controller:
        class: DevTag\KleffmannBundle\Controller\ManagerController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setManagerService, ['@kleffmann.manager.service']]
            - [ setManagerRepository, ['@kleffmann.manager.repository']]

    kleffmann.project_type.controller:
        class: DevTag\KleffmannBundle\Controller\ProjectTypeController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setProjectTypeService, ['@kleffmann.project_type.service']]
            - [ setProjectTypeRepository, ['@kleffmann.project_type.repository']]

    kleffmann.status.controller:
        class: DevTag\KleffmannBundle\Controller\StatusController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setStatusService, ['@kleffmann.status.service']]
            - [ setStatusRepository, ['@kleffmann.status.repository']]

    kleffmann.bank.controller:
        class: DevTag\KleffmannBundle\Controller\BankController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setBankService, ['@kleffmann.bank.service']]
            - [ setBankRepository, ['@kleffmann.bank.repository']]

    kleffmann.training.controller:
        class: DevTag\KleffmannBundle\Controller\TrainingController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setTrainingService, ['@kleffmann.training.service']]
            - [ setTrainingRepository, ['@kleffmann.training.repository']]

    # services
    kleffmann.interviewer.service:
        class: DevTag\KleffmannBundle\Service\InterviewerService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.interviewer_zone.service:
        class: DevTag\KleffmannBundle\Service\InterviewerZoneService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.project.service:
        class: DevTag\KleffmannBundle\Service\ProjectService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.project_zone.service:
        class: DevTag\KleffmannBundle\Service\ProjectZoneService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.project_filter.service:
        class: DevTag\KleffmannBundle\Service\ProjectFilterService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.project_variable.service:
        class: DevTag\KleffmannBundle\Service\ProjectVariableService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.invoice.service:
        class: DevTag\KleffmannBundle\Service\InvoiceService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.customer.service:
        class: DevTag\KleffmannBundle\Service\CustomerService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.manager.service:
        class: DevTag\KleffmannBundle\Service\ManagerService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.project_type.service:
        class: DevTag\KleffmannBundle\Service\ProjectTypeService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.status.service:
        class: DevTag\KleffmannBundle\Service\StatusService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.bank.service:
        class: DevTag\KleffmannBundle\Service\BankService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.training.service:
        class: DevTag\KleffmannBundle\Service\TrainingService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    # repositories
    kleffmann.interviewer.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\Interviewer

    kleffmann.interviewer_zone.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\InterviewerZone

    kleffmann.project.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\Project

    kleffmann.project_zone.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\ProjectZone

    kleffmann.project_filter.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\ProjectFilter

    kleffmann.invoice.repository:
       class: Doctrine\ORM\EntityRepository
       factory_service: doctrine.orm.default_entity_manager
       factory_method: getRepository
       arguments:
           - DevTag\KleffmannBundle\Entity\Invoice

    kleffmann.state.repository:
       class: Doctrine\ORM\EntityRepository
       factory_service: doctrine.orm.default_entity_manager
       factory_method: getRepository
       arguments:
           - DevTag\KleffmannBundle\Entity\State

    kleffmann.customer.repository:
       class: Doctrine\ORM\EntityRepository
       factory_service: doctrine.orm.default_entity_manager
       factory_method: getRepository
       arguments:
           - DevTag\KleffmannBundle\Entity\Customer

    kleffmann.manager.repository:
       class: Doctrine\ORM\EntityRepository
       factory_service: doctrine.orm.default_entity_manager
       factory_method: getRepository
       arguments:
           - DevTag\KleffmannBundle\Entity\Manager

    kleffmann.project_type.repository:
       class: Doctrine\ORM\EntityRepository
       factory_service: doctrine.orm.default_entity_manager
       factory_method: getRepository
       arguments:
           - DevTag\KleffmannBundle\Entity\ProjectType

    kleffmann.status.repository:
       class: Doctrine\ORM\EntityRepository
       factory_service: doctrine.orm.default_entity_manager
       factory_method: getRepository
       arguments:
           - DevTag\KleffmannBundle\Entity\Status

    kleffmann.bank.repository:
       class: Doctrine\ORM\EntityRepository
       factory_service: doctrine.orm.default_entity_manager
       factory_method: getRepository
       arguments:
           - DevTag\KleffmannBundle\Entity\Bank

    kleffmann.training.repository:
       class: Doctrine\ORM\EntityRepository
       factory_service: doctrine.orm.default_entity_manager
       factory_method: getRepository
       arguments:
           - DevTag\KleffmannBundle\Entity\Training