services:
    kleffmann.listener.before_controller:
        class: DevTag\KleffmannBundle\EventListener\BeforeControllerListener
        scope: request
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.controller', method: 'onKernelController' }
        arguments:
            - @security.context

    # controllers
    kleffmann.interviewer.controller:
        class: DevTag\KleffmannBundle\Controller\InterviewerController
        calls:
            - [ setRouter, ['@router']]
            - [ setFormFactory, ['@form.factory']]
            - [ setInterviewerService, ['@kleffmann.interviewer.service']]
            - [ setInterviewerRepository, ['@kleffmann.interviewer.repository']]

    kleffmann.interviewer_zone.controller:
        class: DevTag\KleffmannBundle\Controller\InterviewerZoneController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setInterviewerZoneService, ['@kleffmann.interviewer_zone.service']]
            - [ setInterviewerZoneRepository, ['@kleffmann.interviewer_zone.repository']]

    kleffmann.project.controller:
        class: DevTag\KleffmannBundle\Controller\ProjectController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setProjectService, ['@kleffmann.project.service']]
            - [ setProjectRepository, ['@kleffmann.project.repository']]

    kleffmann.project_zone.controller:
        class: DevTag\KleffmannBundle\Controller\ProjectZoneController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setProjectZoneService, ['@kleffmann.project_zone.service']]
            - [ setProjectZoneRepository, ['@kleffmann.project_zone.repository']]

    kleffmann.project_filter.controller:
        class: DevTag\KleffmannBundle\Controller\ProjectFilterController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setProjectFilterService, ['@kleffmann.project_filter.service']]
            - [ setProjectFilterRepository, ['@kleffmann.project_filter.repository']]

    kleffmann.project_subfilter.controller:
        class: DevTag\KleffmannBundle\Controller\ProjectSubfilterController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setProjectSubfilterService, ['@kleffmann.project_subfilter.service']]
            - [ setProjectSubfilterRepository, ['@kleffmann.project_subfilter.repository']]

    kleffmann.project_variable.controller:
        class: DevTag\KleffmannBundle\Controller\ProjectVariableController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setProjectVariableService, ['@kleffmann.project_variable.service']]
            - [ setProjectVariableRepository, ['@kleffmann.project_variable.repository']]

    kleffmann.invoice.controller:
        class: DevTag\KleffmannBundle\Controller\InvoiceController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setInvoiceService, ['@kleffmann.invoice.service']]
            - [ setInvoiceRepository, ['@kleffmann.invoice.repository']]

    kleffmann.project_type_uprising.controller:
        class: DevTag\KleffmannBundle\Controller\ProjectTypeUprisingController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setProjectTypeUprisingService, ['@kleffmann.project_type_uprising.service']]
            - [ setProjectTypeUprisingRepository, ['@kleffmann.project_type_uprising.repository']]

    # crud
    kleffmann.bank.controller:
        class: DevTag\KleffmannBundle\Controller\BankController
        calls:
            - [ setRouter, ['@router']]
            - [ setFormFactory, ['@form.factory']]
            - [ setService, ['@kleffmann.bank.service']]
            - [ setRepository, ['@kleffmann.bank.repository']]

    kleffmann.customer.controller:
        class: DevTag\KleffmannBundle\Controller\CustomerController
        calls:
            - [ setRouter, ['@router']]
            - [ setFormFactory, ['@form.factory']]
            - [ setService, ['@kleffmann.customer.service']]
            - [ setRepository, ['@kleffmann.customer.repository']]

    kleffmann.manager.controller:
        class: DevTag\KleffmannBundle\Controller\ManagerController
        calls:
            - [ setRouter, ['@router']]
            - [ setFormFactory, ['@form.factory']]
            - [ setService, ['@kleffmann.manager.service']]
            - [ setRepository, ['@kleffmann.manager.repository']]

    kleffmann.status.controller:
        class: DevTag\KleffmannBundle\Controller\StatusController
        calls:
            - [ setRouter, ['@router']]
            - [ setFormFactory, ['@form.factory']]
            - [ setService, ['@kleffmann.status.service']]
            - [ setRepository, ['@kleffmann.status.repository']]

    kleffmann.project_type.controller:
        class: DevTag\KleffmannBundle\Controller\ProjectTypeController
        calls:
            - [ setRouter, ['@router']]
            - [ setFormFactory, ['@form.factory']]
            - [ setService, ['@kleffmann.project_type.service']]
            - [ setRepository, ['@kleffmann.project_type.repository']]

    kleffmann.training.controller:
        class: DevTag\KleffmannBundle\Controller\TrainingController
        calls:
            - [ setFormFactory, ['@form.factory']]
            - [ setRouter, ['@router']]
            - [ setTrainingService, ['@kleffmann.training.service']]
            - [ setTrainingRepository, ['@kleffmann.training.repository']]

    kleffmann.city.controller:
        class: DevTag\KleffmannBundle\Controller\CityController
        calls:
            - [ setCityRepository, ['@kleffmann.city.repository']]

    kleffmann.district.controller:
        class: DevTag\KleffmannBundle\Controller\DistrictController
        calls:
            - [ setDistrictRepository, ['@kleffmann.district.repository']]

    kleffmann.user.controller:
        class: DevTag\KleffmannBundle\Controller\UserController
        calls:
            - [ setRouter, ['@router']]
            - [ setFormFactory, ['@form.factory']]
            - [ setUserService, ['@kleffmann.user.service']]
            - [ setUserRepository, ['@kleffmann.user.repository']]

    # services
    kleffmann.interviewer.service:
        class: DevTag\KleffmannBundle\Service\InterviewerService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.interviewer_zone.service:
        class: DevTag\KleffmannBundle\Service\InterviewerZoneService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.project.service:
        class: DevTag\KleffmannBundle\Service\ProjectService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.project_zone.service:
        class: DevTag\KleffmannBundle\Service\ProjectZoneService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.project_filter.service:
        class: DevTag\KleffmannBundle\Service\ProjectFilterService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.project_subfilter.service:
        class: DevTag\KleffmannBundle\Service\ProjectSubfilterService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.project_variable.service:
        class: DevTag\KleffmannBundle\Service\ProjectVariableService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.invoice.service:
        class: DevTag\KleffmannBundle\Service\InvoiceService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.customer.service:
        class: DevTag\KleffmannBundle\Service\CustomerService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.manager.service:
        class: DevTag\KleffmannBundle\Service\ManagerService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.project_type.service:
        class: DevTag\KleffmannBundle\Service\ProjectTypeService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.project_type_uprising.service:
        class: DevTag\KleffmannBundle\Service\ProjectTypeUprisingService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.status.service:
        class: DevTag\KleffmannBundle\Service\StatusService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.bank.service:
        class: DevTag\KleffmannBundle\Service\BankService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.training.service:
        class: DevTag\KleffmannBundle\Service\TrainingService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    kleffmann.user.service:
        class: DevTag\KleffmannBundle\Service\UserService
        calls:
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]

    # repositories
    kleffmann.interviewer.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\Interviewer
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.interviewer_zone.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\InterviewerZone
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.project.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\Project
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.project_zone.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\ProjectZone
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.project_variable.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\ProjectVariable
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.project_filter.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\ProjectFilter
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.project_subfilter.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\ProjectSubfilter
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.invoice.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\Invoice
        calls:
          - [ setPaginator, ['@knp_paginator']]
          - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.state.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\State

    kleffmann.customer.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\Customer
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.manager.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\Manager
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.project_type.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\ProjectType
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.project_type_uprising.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\ProjectTypeUprising
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.status.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\Status
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.bank.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\Bank
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.training.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\Training
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]

    kleffmann.city.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\City

    kleffmann.district.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\District

    kleffmann.user.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - DevTag\KleffmannBundle\Entity\User
        calls:
            - [ setPaginator, ['@knp_paginator']]
            - [ setRecordsPerPage, ['%records_per_page%']]